import { BarList } from "@/components/bar-list";
import { DemoBanner, StatCard } from "@/components/ui";
import { getAppData } from "@/lib/data";
import { formatDuration } from "@/lib/format";
import { globalStats } from "@/lib/stats";

export const metadata={title:"Estadísticas"}; export const dynamic="force-dynamic";
export default async function StatsPage(){const data=await getAppData();const s=globalStats(data.runs,data.players);return <>{data.isDemo&&<DemoBanner error={data.error}/>}<header className="mb-7"><p className="eyebrow">Sala de récords</p><h1 className="mt-2 text-4xl font-black tracking-tight">Estadísticas</h1><p className="muted mt-2">Las cifras que cuentan nuestra tragedia.</p></header><div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Duración promedio" value={formatDuration(s.averageDuration)}/><StatCard label="Progresión máxima" value={s.bestProgress} accent="gold"/><StatCard label="Llegan al Nether" value={`${s.netherPercentage}%`}/><StatCard label="Llegan al End" value={`${s.endPercentage}%`} accent="gold"/></div>
  <div className="mb-7 grid gap-5 lg:grid-cols-2"><section className="panel p-5 sm:p-6"><h2 className="mb-6 text-xl font-black">Ranking de muertes</h2><BarList items={s.ranking.map(item=>({label:item.player.name,value:item.deaths}))} color="#ff5d62"/>{s.ranking.map(item=><div key={item.player.id} className="mt-3 flex justify-between border-t border-[#263029] pt-3 text-xs text-[#859188]"><span>{item.player.name}</span><span>{item.percentage}% del grupo</span></div>)}</section><section className="panel p-5 sm:p-6"><h2 className="mb-6 text-xl font-black">Muertes por dimensión</h2><BarList items={s.dimensionCounts} color="#bc86ec"/></section></div>
  <section className="panel mb-7 p-5 sm:p-6"><h2 className="mb-6 text-xl font-black">Muertes por causa</h2><BarList items={s.causeCounts} color="#e9595f"/></section>
  <section><p className="eyebrow">Rendimiento individual</p><h2 className="mb-4 mt-2 text-2xl font-black">Quién sobrevive mejor</h2><div className="grid gap-4 md:grid-cols-3">{s.ranking.map(item=><article key={item.player.id} className="panel p-5"><h3 className="text-xl font-black">{item.player.name}</h3><dl className="mt-5 grid gap-3 text-sm"><div className="flex justify-between"><dt className="text-[#849087]">Muertes</dt><dd className="font-bold text-[#ff6f74]">{item.deaths}</dd></div><div className="flex justify-between"><dt className="text-[#849087]">Racha máxima</dt><dd className="font-bold">{item.maxStreak} TRYs</dd></div><div className="flex justify-between"><dt className="text-[#849087]">Racha actual</dt><dd className="font-bold">{item.currentStreak} TRYs</dd></div><div className="flex justify-between"><dt className="text-[#849087]">Dimensión fatal</dt><dd className="font-bold">{item.topDimension}</dd></div><div className="flex justify-between"><dt className="text-[#849087]">Causa frecuente</dt><dd className="font-bold">{item.topCause}</dd></div></dl></article>)}</div></section>
  <section className="mt-8"><p className="eyebrow">Récords</p><h2 className="mb-4 mt-2 text-2xl font-black">El muro de la fama</h2><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="TRY más largo" value={formatDuration(s.longest?.duration_seconds)} detail={s.longest?`TRY #${s.longest.try_number}`:"—"}/><StatCard label="Muerte más rápida" value={formatDuration(s.shortest?.duration_seconds)} detail={s.shortest?`TRY #${s.shortest.try_number}`:"—"} accent="red"/><StatCard label="Causa #1" value={s.topCause} accent="red"/><StatCard label="Dimensión más mortal" value={s.deadliestDimension}/></div></section></>}
