import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Clock3, Flame, Mountain, Trophy, Waves } from "lucide-react";
import { cancelRunAction, completeRunAction, startNextRunAction } from "@/app/actions";
import { DeathDialog } from "@/components/forms";
import { ElapsedTime } from "@/components/elapsed-time";
import { StatCard, StatusBadge } from "@/components/ui";
import { formatDuration, initials } from "@/lib/format";
import { globalStats, playerStats } from "@/lib/stats";
import type { Player, Punishment, Run } from "@/types/database";

function Avatar({ player }: { player: Player }) { return player.avatar_url?<Image src={player.avatar_url} alt="" width={52} height={52} className="size-13 rounded-2xl object-cover"/>:<span className="grid size-13 place-items-center rounded-2xl border border-[#3b4c40] bg-[#1d2921] font-black text-[#83e9a0]">{initials(player.name)}</span>; }

export function DashboardHero({ current, players, isDemo }: { current: Run | null; players: Player[]; isDemo: boolean }) {
  return <section className={`panel grid-pattern relative mb-7 overflow-hidden p-6 sm:p-9 ${current?.status==="completed"?"gold-glow":""}`}><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow mb-3">Minecraft Java · Hardcore Realm</p><h1 className="pixel-shadow text-4xl font-black tracking-[-.05em] sm:text-6xl">MINECRAFT <span className="text-[#ff5d62]">EXTREMO</span></h1>{current?<div className="mt-6 flex flex-wrap items-center gap-3"><span className="text-2xl font-black sm:text-3xl">TRY #{current.try_number.toString().padStart(2,"0")}</span><StatusBadge status={current.status}/>{current.status==="active"&&<ElapsedTime startedAt={current.started_at} className="rounded-full border border-[#314239] bg-[#0b110d] px-3 py-1 font-mono text-sm text-[#b8c6bd]"/>}</div>:<p className="muted mt-5">Todavía no hay TRYs registrados.</p>}</div>
    <div className="flex flex-wrap gap-3 lg:justify-end">{current?.status==="active"?<><DeathDialog players={players} disabled={isDemo}/><form action={completeRunAction}><button disabled={isDemo} className="btn btn-gold"><Trophy size={19}/> COMPLETAMOS EL JUEGO</button></form><form action={cancelRunAction}><button disabled={isDemo} className="btn btn-ghost text-sm">Cancelar TRY</button></form></>:<form action={startNextRunAction}><button disabled={isDemo} className="btn btn-primary px-7"><Flame size={19}/> INICIAR SIGUIENTE TRY</button></form>}</div></div></section>;
}

export function PlayerCards({ players, runs }: { players: Player[]; runs: Run[] }) { return <section className="mb-8"><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">El equipo</p><h2 className="mt-2 text-2xl font-black">Supervivientes</h2></div><span className="text-xs text-[#68746c]">la muerte de uno termina el TRY</span></div><div className="grid gap-4 md:grid-cols-3">{players.map(player=>{const stats=playerStats(player,runs);return <article key={player.id} className="panel p-5"><div className="mb-5 flex items-center gap-3"><Avatar player={player}/><div><h3 className="text-lg font-black">{player.name}</h3><p className="text-sm text-[#748078]">{player.nickname??"Sin nickname"}</p></div></div><div className="grid grid-cols-2 gap-3"><div><p className="text-2xl font-black text-[#ff696e]">☠ {stats.deaths}</p><p className="text-xs text-[#7f8d84]">muertes · {stats.percentage}%</p></div><div><p className="text-2xl font-black text-[#f4bd51]">{stats.currentStreak}</p><p className="text-xs text-[#7f8d84]">TRYs de racha</p></div></div><div className="mt-5 grid grid-cols-3 divide-x divide-[#293129] border-t border-[#293129] pt-4 text-center text-xs"><div><Mountain size={14} className="mx-auto mb-1 text-[#70ce8c]"/><strong>{stats.overworld}</strong><span className="block text-[#69766e]">Overworld</span></div><div><Flame size={14} className="mx-auto mb-1 text-[#ed735b]"/><strong>{stats.nether}</strong><span className="block text-[#69766e]">Nether</span></div><div><Waves size={14} className="mx-auto mb-1 text-[#bd8cf0]"/><strong>{stats.end}</strong><span className="block text-[#69766e]">The End</span></div></div></article>})}</div></section>; }

export function GlobalCards({ runs, players }: { runs: Run[]; players: Player[] }) { const s=globalStats(runs,players); return <section className="mb-8"><p className="eyebrow">Panorama general</p><h2 className="mb-4 mt-2 text-2xl font-black">La expedición en números</h2><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="TRYs totales" value={s.totalRuns}/><StatCard label="Muertes" value={s.totalDeaths} accent="red"/><StatCard label="Mejor progreso" value={s.bestProgress} accent="gold"/><StatCard label="Tiempo jugado" value={formatDuration(s.totalDuration)}/><StatCard label="TRY más largo" value={formatDuration(s.longest?.duration_seconds)} detail={s.longest?`TRY #${s.longest.try_number}`:"—"}/><StatCard label="TRY más corto" value={formatDuration(s.shortest?.duration_seconds)} detail={s.shortest?`TRY #${s.shortest.try_number}`:"—"} accent="red"/><StatCard label="Llegadas al Nether" value={s.netherReached}/><StatCard label="Victorias" value={s.victories} accent="gold"/></div></section>; }

export function PunishmentAlert({ punishment, runs }: { punishment: Punishment; runs: Run[] }) { const involved=punishment.run_ids.map(id=>runs.find(run=>run.id===id)).filter(Boolean) as Run[]; return <section className="panel danger-glow mb-8 overflow-hidden border-[#6c2b30] bg-gradient-to-br from-[#2b1214] to-[#121311] p-6 sm:p-7"><div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="mb-2 text-xs font-black tracking-[.18em] text-[#ff6e73]">🚨 CASTIGO DESBLOQUEADO</p><h2 className="text-2xl font-black">Los otros dos deben elegir una Nota de Instagram para {punishment.punished_player?.name??"el culpable"}.</h2><div className="mt-4 flex flex-wrap gap-2">{involved.map(run=><span key={run.id} className="rounded-full border border-[#5c2c2e] bg-[#240f11] px-3 py-1 text-xs text-[#e9b1b3]">TRY #{run.try_number} · {run.dead_player?.name}</span>)}</div></div><Link href="/punishments" className="btn btn-danger">Resolver castigo <ArrowRight size={17}/></Link></div></section>; }

export function RecentRuns({ runs }: { runs: Run[] }) { const recent=runs.slice(0,5); return <section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Última actividad</p><h2 className="mt-2 text-2xl font-black">Historial reciente</h2></div><Link href="/history" className="flex items-center gap-2 text-sm font-bold text-[#72dc91]">Ver todo <ArrowRight size={16}/></Link></div><div className="grid gap-3">{recent.map(run=><Link href={`/history/${run.id}`} key={run.id} className="panel flex flex-wrap items-center gap-4 p-4 transition hover:border-[#465349]"><span className="grid size-12 place-items-center rounded-xl bg-[#171d19] font-black">#{run.try_number}</span><div className="min-w-48 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>TRY #{run.try_number}</strong><StatusBadge status={run.status}/></div><p className="mt-1 text-sm text-[#859188]">{run.status==="failed"?`${run.dead_player?.name??"Alguien"} murió por ${run.death_cause}`:run.status==="active"?"La aventura continúa":run.status==="completed"?"El dragón cayó":"Intento corregido/cancelado"}</p></div><span className="flex items-center gap-2 text-sm text-[#849087]"><Clock3 size={15}/>{run.status==="active"?<ElapsedTime startedAt={run.started_at}/>:formatDuration(run.duration_seconds)}</span><ArrowRight size={18} className="text-[#56615a]"/></Link>)}</div></section>; }
